### ISSUE TITLE
Polymath stops working until platform restart

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#39]
I started getting this error and had to restart the platform to get it working again:

Action ID: Polymath_qcOgG4Cu_0

Action Target: 09c1ad51-f3ac-4142-a63e-85b0dac47494

Action Parameters:
add_to_collection_id: a13d38af-8a66-447e-a345-c06b569bf302
beats_per_loop: 4
classify: true
embed: true
loopify: true
n_loops: 4
quantize: false
quantize_to_bpm: 120
stem_types: [ "vocals", "drums", "bass", "other" ]
stemify: true
target_id: 9815c92d-3360-4878-8295-75ce0fb29296
Action Errors:
Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func raise Exception(err_log) Exception: [' plugin_instance = self._load_plugin(module_name=module_name)', ' File "/home/nendo/.local/lib/python3.8/site-packages/nendo/main.py", line 129, in _load_plugin', ' raise schema.NendoPluginLoadingError( # noqa: B904', "nendo.schema.exception.NendoPluginLoadingError: Failed to import plugin 'nendo_plugin_classify_core'. Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))", '']

maybe the server has a timeout set?

**Comment by faradox** [comment]
Seems related to https://github.com/okio-ai/nendo-platform/issues/28 Please check that it's not a connection issue. We are working on adding some retry code and a more informative error message to make it clearer that this is a connection issue to the remote server where the model is downloaded from.

**Comment by faradox** [comment]
Closing this thread due to inactivity
