### ISSUE TITLE
Music analysis fails on library

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#40]
After processing the whole library I get a fail with music analysis:

Action ID: Music_Analysis_are7Gdh3_0

Action Target:

Action Parameters:
target_id:
Action Errors:
Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func raise Exception(err_log) Exception: ['WHERE collections.id = %(id_1)s::UUID ', ' LIMIT %(param_1)s]', "[parameters: {'id_1': '', 'param_1': 1}]", '(Background on this error at: https://sqlalche.me/e/20/9h9h)', '']

**Comment by faradox** [comment]
That's my bad. I just commited a fix for that. Please update your Nendo and try again.
