### ISSUE TITLE
audio stops working when idle

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#57]
If I leave the platform idle for an amount of time (20 min?) All of the audio playback is broken until I restart the server

**Comment by jhurlbut** [comment]
Also if I leave the server on overnight I get this error the next day when trying to run tasks:

18:18:47 [Job Music_Generation_N1QBVaa8_0]: exception raised while executing (handler.nendo_actions_handler.dockerized_func)
nendo-server    | Traceback (most recent call last):
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job
nendo-server    |     rv = job.perform()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform
nendo-server    |     self._result = self._execute()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute
nendo-server    |     result = self.func(*self.args, **self.kwargs)
nendo-server    |   File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 203, in dockerized_func
nendo-server    |     raise Exception(err_log)
nendo-server    | Exception: ['    return _open_file(name_or_buffer, mode)', '  File "/home/nendo/.local/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__', '    super().__init__(open(name, mode))', "FileNotFoundError: [Errno 2] No such file or directory: '/home/nendo/.cache/nendo/models/musicgen/085df796-cb6b-4251-9d17-758c720114e5/StrictlyTraining/ShinyKnightsSingShiny/state_dict.bin'", '']
