### ISSUE TITLE
music analysis always fails now

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#68]
just did make update and build-dev and now music analysis always fails:

Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 203, in dockerized_func raise Exception(err_log) Exception: ['Traceback (most recent call last):', ' File "run.py", line 14, in <module>', ' from wrapt_timeout_decorator import timeout', "ModuleNotFoundError: No module named 'wrapt_timeout_decorator'", '']

**Comment by jhurlbut** [comment]
running make setup-dev fixes it. Would it be difficult to configure make setup-dev to only update changed depencies? It takes over an hour to run for me.

**Comment by jhurlbut** [comment]
wtf is this ai doing in github?

**Comment by boringtaskai** [comment]
I mean you can make a  new rule in the Makefile to build each dependecies and the create PR, since if you run `make setup-dev`, it will call these rules, that's why you wait 1 hr.

init-dev 
update 
build-dev 
build-tools-gpu-dev


Cheers
Your AI Nightmare

**Comment by faradox** [comment]
I advise you not to try and build the tools using the `docker` commands found in the `Makefile` directly. Especially building the Nendo core image will not work if called directly like you suggested in your reply, @boringtaskai .

That being said, the `make setup-dev` command is already only building those images that need to be built to activate the latest changes in any of the repositories. This particular time, a new dependency was added to the Nendo core image, from which all tool images are derived, thus they all had to be built aswell, which takes a bit of time. We have to use separate `docker` images for the tools to avoid dependency conflicts and deriving them all from a common core image is the most efficient approach I've come up with so far. Any suggestions for improvements are welcome but for now, the current system has to do.

Closing this thread now.
