### ISSUE TITLE
Polymath error

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#69]
Getting this new error:

Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 203, in dockerized_func raise Exception(err_log) Exception: ['[2024-03-13T12:06:27.563Z] nendo DEBUG Loop buffer shape: (2, 159642)', '[2024-03-13T12:06:27.579Z] nendo DEBUG Loop buffer shape: (2, 171108)', '[2024-03-13T12:06:33.796Z] nendo DEBUG Loaded track with shape (2, 69497697) and sample rate 48000.', '[2024-03-13T12:06:33.796Z] nendo DEBUG Resampling track from 48000 to 44100.', '']

**Comment by faradox** [comment]
That's strange, it seems like the loopifier fails on the downsampling step, possibly because your track is very long (24 minutes if I'm correct?). The problem is that the message you posted does not contain an actual error, only debug outputs. Are you sure that you copied the entire error message?
