### ISSUE TITLE
MusicGen Training not working

### ISSUE THREAD

**Issue by boringtaskai** [okio-ai/nendo-platform#71]
I tried to use MusicGen Training Plugin, but I got these errors,  and then the MusicGenTrain container exited, 

--- begin the log message ---

2024-03-21 00:05:25 [2024-03-20T18:05:25.020Z] numba.core.ssa         DEBUG SSA violators set()
2024-03-21 00:06:10 1 Physical GPUs, 1 Logical GPUs
2024-03-21 00:06:10 collection/751a7e72-00d2-476f-a348-1b0521e4db82
2024-03-21 00:06:10 Traceback (most recent call last):
2024-03-21 00:06:10   File "run.py", line 190, in <module>
2024-03-21 00:06:10     main()
2024-03-21 00:06:10   File "run.py", line 159, in main
2024-03-21 00:06:10     nd.plugins.musicgen.train(
2024-03-21 00:06:10   File "/home/nendo/.local/lib/python3.8/site-packages/nendo/schema/core.py", line 1888, in __getattr__
2024-03-21 00:06:10     raise NendoPluginRuntimeError(
2024-03-21 00:06:10 nendo.schema.exception.NendoPluginRuntimeError: Plugin nendo_plugin_musicgen has no function train

--- end of log message ---

**Comment by faradox** [comment]
This is most likely due to an outdated docker build cache.

Please call the following:

```
docker image rm nendo/musicgen ; docker image rm nendo/musicgentrain ; docker build prune ; make build-tools-gpu
```

**Comment by boringtaskai** [comment]
It works, i rebuild and prune the cache, using your command. Thanks
